package com.yatatsu.fieldschema.processor;

import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.TypeSpec;

import java.io.IOException;
import java.util.List;


public abstract class BaseCodeWriter<T> {

    public static final String TARGET_CLASS_NAME = "FS";
    private final List<T> holders;

    BaseCodeWriter(List<T> holders) {
        this.holders=holders;
    }

    public void write(String packageName, TypeSpec.Builder typeSpecBuilder) throws IOException
    {
        typeSpecBuilder.addJavadoc(
                "FieldSchema\n\n" + "This is auto generated by FieldSchema. Do not modify.\n");
        holders.stream().map(this::createFieldSpec)
                .forEach(typeSpecBuilder::addField);
    }

    public abstract FieldSpec createFieldSpec(T holder);
}
